patc
Korg 05R/W
05R/W
Sunrise      
Piano 16'   
AltoBreath  
TinyDancer  
Spruce Gtr  
Vibra Bell  
Xfade Bass
TheStrings
PowerSynth 
Total Kit  
MachineAge  
HotKeys     
Brass Band  
Maxi Tine    
Power Rock  
Tabla Talk
FingerBass  
LiteVoices
Color Pad 
Festival! 
GlideSweep  
Last Tango  
MagicFlute  
Operators   
E.Guitars   
Gamelan    
Zap Bass  
DigitalAir
Analogist 
MandoTrem 
Space Wing  
GospelOrg   
Trumpets    
Fresh Air   
Rock Mutes  
Dustette  
PickedBass  
ChamberEns
Wire Pad  
Industrial
Neutron    
PianoHaven  
Shaku Bend  
BowenWave  
Clean Funk  
SplitBell   
Slap It   
AnalogPad 
Residue   
Orch Perc  
DreamWorld  
HarpsiFunk  
FlugelHorn  
Elec. Tap   
Harmonics   
Africana   
TechnoBass 
Airways   
Busy Boy  
Heartbeat 
Spectrum  
Full Pipes  
Woodwinds   
Whirly      
LeadGutar   
Isabelle    
FatFretty 
Poppin'Pad
Soft Horns  
ProducrKit 
InTheTrees  
SantaClav   
Sfz< Brass  
Tine Pad     
PedalSteel  
Log Drums   
HouseBass1
Ambi.Voice
MonoLead   
Hackbrett  
Halifax NS  
Drawbars    
Fanfare     
Hard Tines   
Dr.Guitar   
EtherBells  
Bass/Harm   
Air Vox    
Drum Hit  
50's SciFi 
SteamCloud  
Bouzouki    
BriteBrass  
DWGS EP     
JoyStickUp  
WaveCycles  
Rap Bass   
OoooohPad  
Bright Pad 
HarpPluck  
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
