patc
Roland D-110
D110
AcouPiano 1
AcouPiano 2
AcouPiano 3
Honky Tonk
ElecPiano 1
ElecPiano 2
ElecPiano 3
ElecPiano 4
ElecOrgan 1
ElecOrgan 2
ElecOrgan 3
ElecOrgan 4
PipeOrgan 1
PipeOrgan 2
PipeOrgan 3
Accordion
Harpsi 1
Harpsi 2
Harpsi 3
Clav 1
Clav 2
Clav 3
Celesta 1
Celesta 2
Violin 1
Violin 2
Cello 1
Cello 2
Contrabass
Pizzicato
Harp 1
Harp 2
Strings 1
Strings 2
Strings 3
Strings 4
Brass 1
Brass 2
Brass 3
Brass 4
Trumpet 1
Trumpet 2
Trombone 1
Trombone 2
Horn
Fr Horn
Engl Horn
Tuba
Flute 1
Flute 2
Piccolo
Recorder
Pan Pipes
Bottleblow
Breathpipe
Whistle
Sax 1
Sax 2
Sax 3
Clarinet 1
Clarinet 2
Oboe
Bassoon
Harmonica
Fantasy
Harmo Pan
Chorale
Glasses
Soundtrack
Atmosphere
Warm Bell
Space Horn
Echo Bell
Ice Rain
Oboe 2001
Echo Pan
Bell Swing
Roso Synth
Stream Pad
Vibe String
Syn Lead 1
Syn Lead 2
Syn Lead 3
Syn Lead 4
Syn Bass 1
Syn Bass 2
Syn Bass 3
Syn Bass 4
Acou Bass 1
Acou Bass 2
Elec Bass 1
Elec Bass 2
Slap Bass 1
Slap Bass 2
Fretless 1
Fretless 2
Vibe
Glock
Marimba
Xylophone
Guitar 1
Guitar 2
Elec Gtr 1
Elec Gtr 2
Koto
Shamisen
Jamisen
Sho
Shakuhachi
Wadaiko Set
Sitar
Steel Drum
Tech Snare
Elec Tom
Reverse Cym
Ethno Hit
Timpani
Triangle
Wind Bell
Tube Bell
Orch Hit
Bird Tweet
OneNoteJam
Telephone
Typewriter
Insect
Water Bells
Jungle Tune
