patc
Evolution EVS-1
EVS1
Jump Brass
Chimes
WarmString
HipHopBass
ChorusOrgn
El Piano 1
AllTheBizz
Ethereal
Chorus
SynBrass 1
X7 Bass
VelsoftBrs
DeepString
SynBrass 2
El Piano 2
Synth Clav
Syn Bass
BowedVocal
NyloGuitar
PluckedStr
Reedy
SynthHorns
SawString
BloozyBox
Swishy
WireGuitar
Low Bass
SynthEdge
Afro
SoftChimes
MetalBrass
Brassoo
WarmStrng2
Keyboardo
Analogue 3
SynHarpsi
BoomBass
MetalKeys
SweepSynth
BellOrgan
PanFlute
BrassPad
Pythagorus
Bass n Pno
PipePuipe
Sunbrero
Bass
SynthModWh
Chapel
MalletBrth
BassyBrass
Trumpet
Bach to me
Prunklett
Hefern
Clavrozog
Elec Bass
Greenbar
VocalStrng
Cajoladox
Chattring
KindaBell
OrchString
ShowOff
StabAnalog
Shorty
ZingBass
Pixie
HeySpike
WarmStrng3
SynBrass3
Marimba
League 1
Funshious
Wibble
Swamp
Housebass
Pretty
Ostende
HarpSitar
Plinkety
EinStein
DistGuitar
Dissonant
Harpsichod
Chime Pno
Pad Bass
TightBass
Guitar
Swellbells
Analogue
SoftPad
CoolSound
Falling
Orbital
Orchestral
Synth1992
ChorStrPad
Drumkit 1
Drumkit 2
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
