patc
General MIDI
GM
Acou Grand Piano
Bright Acou Piano
Elec Grand Piano
Honky-tonk Piano
Electric Piano 1
Electric Piano 2
Harpsichord
Clavinet
Celesta
Glockenspiel
Music Box
Vibraphone
Marimba
Xylophone
Tubular Bells
Dulcimer
Drawbar Organ
Percussive Organ
Rock Organ
Church Organ
Reed Organ
Accordion
Harmonica
Tango Accordion
Nylon Acou Guitar
Steel Acou Guitar
Jazz Elec Guitar
Clean Elec Guitar
Muted Elec Guitar
Overdrive Guitar
Distorted Guitar
Guitar Harmonics
Acoustic Bass
Elec Bass Fingered
Elec Bass Picked
Fretless Bass
Slap Bass 1
Slap Bass 2
Syn Bass 1
Syn Bass 2
Violin
Viola
Cello
Contrabass
Tremolo Strings
Pizz Strings
Orchestral Harp
Timpani
String Ensemble 1
String Ensemble 2
Syn Strings 1
Syn Strings 2
Choir Aahs
Voice Oohs
Syn Choir
Orchestra Hit
Trumpet
Trombone
Tuba
Muted Trumpet
French Horn
Brass Section
Syn Brass 1
Syn Brass 2
Soprano Sax
Alto Sax
Tenor Sax
Baritone Sax
Oboe
English Horn
Bassoon
Clarinet
Piccolo
Flute
Recorder
Pan Flute
Bottle Blow
Shakuhachi
Whistle
Ocarina
Syn Square Wave
Syn Saw Wave
Syn Calliope
Syn Chiff
Syn Charang
Syn Voice
Syn Fifths
Syn Bass+Lead
Newage Syn Pad
Warm Syn Pad
PolySyn Pad
Syn Choir Pad
Bowed Syn Pad
Metal Syn Pad
Halo Syn Pad
Syn Sweep Pad
SFX Rain
SFX Soundtrack
SFX Crystal
SFX Atmosphere
SFX Brightness
SFX Goblins
SFX Echoes
SFX Sci-fi
Sitar
Banjo
Shamisen
Koto
Kalimba
Bag Pipe
Fiddle
Shanai
Tinkle Bell
Agogo
Steel Drums
Woodblock
Taiko Drum
Melodic Tom
Syn Drum
Reverse Cymbal
Guitar Fret Noise
Breath Noise
Seashore
Bird Tweet
Telephone Ring
Helicopter
Applause
Gun Shot
