patc
GS Normal Voices
GS
Acou Grand Piano
Bright Acou Piano
Elec Grand Piano
Honky-tonk Piano
Electric Piano 1
Electric Piano 2
Harpsichord
Clavinet
Celesta
Glockenspiel
Music Box
Vibraphone
Marimba
Xylophone
Tubular Bells
Dulcimer
Drawbar Organ
Percussive Organ
Rock Organ
Church Organ
Reed Organ
Accordion
Harmonica
Tango Accordion
Nylon Acou Guitar
Steel Acou Guitar
Jazz Elec Guitar
Clean Elec Guitar
Muted Elec Guitar
Overdrive Guitar
Distorted Guitar
Guitar Harmonics
Acoustic Bass
Elec Bass Fingered
Elec Bass Picked
Fretless Bass
Slap Bass 1
Slap Bass 2
Syn Bass 1
Syn Bass 2
Violin
Viola
Cello
Contrabass
Tremolo Strings
Pizz Strings
Orchestral Harp
Timpani
String Ensemble 1
String Ensemble 2
Syn Strings 1
Syn Strings 2
Choir Aahs
Voice Oohs
Syn Choir
Orchestra Hit
Trumpet
Trombone
Tuba
Muted Trumpet
French Horn
Brass Section
Syn Brass 1
Syn Brass 2
Soprano Sax
Alto Sax
Tenor Sax
Baritone Sax
Oboe
English Horn
Bassoon
Clarinet
Piccolo
Flute
Recorder
Pan Flute
Bottle Blow
Shakuhachi
Whistle
Ocarina
Syn Square Wave
Syn Saw Wave
Syn Calliope
Syn Chiff
Syn Charang
Syn Voice
Syn Fifths
Syn Bass+Lead
Newage Syn Pad
Warm Syn Pad
PolySyn Pad
Syn Choir Pad
Bowed Syn Pad
Metal Syn Pad
Halo Syn Pad
Syn Sweep Pad
SFX Rain
SFX Soundtrack
SFX Crystal
SFX Atmosphere
SFX Brightness
SFX Goblins
SFX Echoes
SFX Sci-fi
Sitar
Banjo
Shamisen
Koto
Kalimba
Bag Pipe
Fiddle
Shanai
Tinkle Bell
Agogo
Steel Drums
Woodblock
Taiko Drum
Melodic Tom
Syn Drum
Reverse Cymbal
Guitar Fret Noise
Breath Noise
Seashore
Bird Tweet
Telephone Ring
Helicopter
Applause
Gun Shot
*Var1
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Synth Bass 101
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Trombone 2
-
-
French Horn 2
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Square
Saw
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Gt. Cut Noise
Fl. Key Click
Rain
Dog
Telephone 2
Car-Engine
Laughing
Machine Gun
*Var2
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
String Slap
-
Thunder
Horse-Gallop
DoorCreaking
Car-Stop
Screaming
Lasergun
*Var3
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Wind
Bird 2
Door
Car-Pass
Punch
Explosion
*Var4
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Stream
-
Scratch
Car-Crash
Heart Beat
*Var5
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Bubble
-
Windchime
Siren
Footsteps
*Var6
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Train
*Var7
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
JetPlane
*Var8
Piano 1w
Piano 2w
Piano 3w
Honky-tonk w
Detuned EP 1
Detuned EP 2
Coupled Hps.
-
-
-
-
Vib.w
Marimba w
-
Church Bell
-
Detuned Or. 1
Detuned Or. 2
-
Church Org. 2
-
Accordian It
-
-
Ukelele
12-str.Gt.
Hawaiian Gt.
Chorus Gt.
Funk Gt.
-
Feedback Gt.
Gt. Feedback
-
-
-
-
-
-
Synth Bass 3
Synth Bass 4
Slow Violin
-
-
-
-
-
-
-
Orchestra
-
Syn. Strings3
-
-
-
-
-
-
-
-
-
-
Brass 2
Synth Brass3
Synth Brass4
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Sine Wave
Doctor Solo
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Taisho Koto
-
-
-
-
-
-
-
Castanets
Concert BD
Melo. Tom 2
808 Tom
-
-
-
-
-
-
Starship
*Var9
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Carillon
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Burst Noise
*
*
*
*
*
*
*Var16
Piano 1d
-
-
-
E. Piano 1v
E. Piano 2v
Harpsi.w
-
-
-
-
-
-
-
-
-
60's Organ1
-
-
Church Org. 3
-
-
-
-
Nylon Gt.o
Mandolin
-
-
Funk Gt.2
-
-
-
-
-
-
-
-
-
-
Rubber Bass
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
AnalogBrass2
*
*
*
*
*
*
*
*Var24
-
-
-
-
60's Piano
-
Harpsi.o
*
*
*
*
*
*
*
*Var32
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Organ 4
Organ 5
-
-
-
-
-
-
Nylon Gt.2
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Choir Aahs 2