patc
Roland JV1080 
1080_User
Symphonique                  
Alternative           
Velo Tekno 1          
West Coast            
Albion                
Jz Gtr Hall           
Rocker Spin           
101 Bass              
Claviduck             
Jet Pad 2             
Raggatronic           
Crunch Split          
Running Pad           
Brass Sect            
Flying Waltz          
Pure Tibet            
4 Hits 4 You          
Waterhodes            
Blade Racer           
JC Strat              
Dawn 2 Dusk           
Saw Mass              
Steel Away            
64voicePiano          
Wave Bells            
IP-8Haunting          
Vanishing             
Harmonica             
Film Octaves          
Edye boost            
AugerMentive          
Deep Strings          
Chime Wash            
SA Rhodes 1           
3D Flanged            
Ac.Upright            
Poly Brass            
Dissimilate           
Dulcimer              
Fantasy Vox           
Dist Gtr 1            
Sax Section           
Aurora                
St.Strings            
AmbienceVibe          
Cascade               
AltoLead Sax          
PWM Strings           
Childlike             
Velo Tekno 2          
Taj Mahal             
D-50 Stack            
ChamberWoods          
Pulse Key             
Mondo Bass            
Velo-Wah Gtr          
Sitar                 
Purple Spin           
RandomVowels          
Big BPF               
Dunes                 
Heirborne             
PsychoRhodes          
Tortured              
Bass Marimba   
Syncrosonix    
MandolinTrem   
Poly Saws      
Pulse Pad      
Nylon Gtr      
ORBit Pad      
Majestic Tpt   
Terminate      
SquareLead 1   
House Piano    
Fooled Again   
Pick Bass      
Wide Tubular   
Velo-Rez Clv   
Airplaaane     
Delicate EP    
Rezoid         
E-Motion Pad   
Phripphuzz     
Archimede      
Intentions     
Nylon Rhodes   
Huff N Stuff   
Finger Bass    
Gospel Svin    
Harmonicum     
Impact         
Rotary Gtr     
Tp&Sax Sect    
Tubular Vox    
Sawteeth       
Ocean Floor    
E.Grand        
Clarinet mp    
Bass In Face   
BritelowBass   
Mellow Bars    
LetterFrmPat   
MG Solo        
Air Lead       
Raya Shaku     
Greek Power    
Biosphere      
EP+Mod Pad     
Chambers       
Nomad Perc     
Horn Swell     
Hillbillys     
Night Shade    
Nice Piano     
VOX Flute      
Music Bells    
JUNO Strings   
Bs/Pno+Brs     
Dark Vox       
Bass Pizz      
Seq Mallet     
Variable Run   
Cvber Space    
12str Gtr 1    
PianoStrings   
Sands of Time  
Fantasia JV