patc
Roland JV1080
1080_b
Dist Gtr 1            
Dist Ctr 2     
R&R Chunk      
Phripphuzz     
Grungeroni     
Black Widow    
Velo-Wah Gtr   
Mod-Wah Gtr    
Pick Bass      
Hip Bass      
Perc.Bass     
Homey Bass    
Finger Bass   
Nylon Bass    
Ac.Upright    
Wet Fretls    
Fretls Dry    
Slap Bass 1   
Slap Bass 2   
Slap Bass 3   
Slap Bass 4   
4 Pole Bass   
Tick Bass     
House Bass    
Mondo Bass    
Clk AnalogBs  
Bass In Face  
101 Bass      
Noiz Bass     
Super Jup Bs  
Occitan Bass  
Hugo Bass     
Multi Bass    
Moist Bass    
BritelowBass  
Untamed Bass  
Rubber Bass   
Stereoww Bs   
Wonder Bass   
Deep Bass     
Super JX Bs   
W<RED>Bass    
HI-Ring Bass  
Euro Bass     
SinusoidRave  
Alternative   
Acid Line     
Auto TB-303   
Hihat Tekno   
Velo Tekno 1  
Raggatronic     
Blade Racer   
S&H Pad       
Svncrosonix      
Fooled Again  
Alive         
Velo Tekno 2  
Rezoid        
Raverborg     
Blow Hit      
Hammer Bell   
Seq Mallet    
Intentions    
Pick It       
Analog Seq  
Impact Vox
TeknoSoloVox
X-Mod Man
Paz <==> Zap
4 Hits 4 You
Impact
Phase Hit
Tekno Hit 1
Tekno Hit 2
Tekno Hit 3
Reverse Hit
SquareLead 1
SquareLead 2
You and Luck
Belly Lead
WhistlinAtom
Edye Boost
MG Solo
FXM Saw Lead
Sawteeth
Smoothe
MG Lead
MG Interval
Pulse Lead 1
PuIse Lead 2
Little Devil
Loud SynLead
Analog Lead
5th Lead
Flute
Piccolo
VOX Flute
Air Lead
Pan Pipes
AirPlaaane
Taj Mahal
Rava Snaku
Oboe mf
Oboe Express
Carinet mp
ClariExPress
Mitzva Split
ChamberWinds
ChamberWoods
Film Orch
Sop.Sax mf
AltoSax
AltoLead Sax
Tenor Sax
Baritone Sax
Take A Tenor
Sax Section
Bigband Sax 
Harmonica
Harmo Blues
BluesHarp 
Hillbillys
French Bags
Majestic Tpt
Voluntare
2Trumpets
Tpt Sect
Mute TP mod
