patc
Roland JV-80 / 880
JV80
A. Piano 1
A. Piano 2
Mellow Piano
Pop Piano 1
Pop Piano 2
Pop Piano 3
MIDIed Grand
Country Bar
Glist El Pno
MIDI E Piano
SA Rhodes
Dig Rhodes 1
Dig Rhodes 2
Stiky Rhodes
Guitr Rhodes
Nylon Rhodes
Clav 1
Clav 2
Marimba
Marimba SW
Warm Vibe
Vibe
Wave Bells
VibroBell
Pipe Organ 1
Pipe Organ 2
Pipe Organ 3
E. Organ 1
E. Organ 2
Jazz Organ 1
Jazz Organ 2
Metal Organ
Nylon Gtr 1
Flanged Nylon
Steel Guitar
PickedGuitar
12 strings
Velo Harmnix
Nylon+Steel
SwitchOnMute
JC Strat
Stratus
Syn Strat
Pop Strat
Clean Strat
Funk Gtr
Syn Guitar
Overdrive
Fretless
St Fretless
Woody Bass1
Woody Bass2
Analog Bs 1
House Bass
Hip Bass
RockOut Bass
Slap Bass
Thumpin Bass
Pick Bass
Wonder Bass
Yowza Bass
Rubber Bs 1
Rubber Bs 2
Stereoww Bs
Pizzicato
Real Pizz
Harp
SoarinString
Warm Strings
Marcato
St Strings
Orch Strings
Slow Strings
Velo Strings
BrightStrngs
TremoloString
Orch Stab 1
Brite Stab
JP-8 Strings
String Synth
Wire Strings
New Age Vox
Arasian Morn
Beauty Vox
Vento Voxx
Pvox Oooze
GlassVoices
Space Ahh
Trumpet
Trombone
Harmon Mute 1
Harmon Mute 2
TeaJay Brass
Brass Sect 1
Brass Sect 2
Brass Swell
Brass Combo
Stab Brass
Soft Brass
Horn Brass
French Horn
AltoLead Sax
Alto Sax
Tenor Sax 1
Tenor Sax 2
Sax Section
Sax Tp Tb
FlutePiccolo
Flute mod
Ocarina
OverblownPan
Air Lead
Steel Drum
Log Drum
Box Lead
Soft Lead
Whistle
Square Lead
Touch Lead
NightShade
Pizza Hutt
EP+Exp Pad
JP-8 Pad
Puff
SpaciosSweep
Big n Beefy
RevCymBend
Analog Seq
