patc
Kurzweil K1000
K1000
Grand Piano
Fast Strings
Choir
Vibes
Acoustic Bass
Trumpet
Baritone Horn
Clarinet
Electric Organ
Rock Organ
Jazz Organ 1
Electric Piano
Digital Elec Piano
Piano & Elec Piano
Bright Piano
Stereo Grand Piano
Stereo Extd Piano
Bass / Piano 1
Bass / Piano 2
Piano&Slow Strings
Chorused Piano
New Age Piano
Octave Piano
Slow Strings
Medium Strings
Fast Strings + Rel
SlowtoFast Strings
Hall Strings
Synth Strings 1
Bell & Strings
Flanged Strings
Cathedral Choir
Choir & Strings
Bell & Choir
Fluid Vibes
Stereo Trem Vibe
Super Vibes
Slow Vibes
Vibes & Elec Piano
Bowed Acoustc Bass
Synth Bass
Slap Bass
Pipe Organ
Dynamic Elec Organ
Dynamic Rock Organ
Dynamic Jazz Organ
Organ w/Wheslie
Jazz Organ 2
Trumpet Section
Analog Brass
Handbells
Synth Harpsi 1
Synth Kalimba
Klavinyet
Fat Synth
Bells with Echo
Chelodes
Strhodes
Electric Piano 2
Digital El Piano 2
Synth Pizz 1
Synth Pizz 2
Synth Strings 2
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
