patc
Kawai K1-II
K1-II
Hello !!
Classic Gt
WarmStrings
Real Rhodes
Return Home
Tenor Sax
Fender Bass
Seagulls
Piano
Ebony & Ivory
Jazz Harp
Reso Clav
N.Larsen
Oboe
Trumpet
String Oct
Stratos
India Town
OB-Brass
Wine Glass
Crockett's
Jan's Dog
Voice
Quazy-Moto
Ac Bass
Techno Bass
Kick Bass 2
Bottles
Elec Kick
E. Tom
Water Drama
Super Jet
Ahh-II
12 String
Analog Strings
Xylimba
Visitors
Clarinet
That Bass
Pistol<-----
Piano 1
Chorus Piano
Kimono
Sunthicord
Big Pipe
Pan Flute
French Horn
Orchestral
Dist. Guitar
Shakazulu
Persnl Brs
Bell Air
Heavey Hitte
Axel
Syn Voices
Lucky Man
Fretlezz
Syn Brass
MuteBass
BottleBell
Crash Kick
RockSnr
Halloween
Doppler
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
