patc
Korg M1
M1
Universe
Piano 16'
Brass 1
Ooh/Aah
Guitar 1
BottleBell
Fretless
Symphonic
PanFlute
Drums #1
PanMallet
E.Piano 1
Trumpet
Nimbus
DistGuitar
Vibes
Pick Bass
Organ 2
Flute
Pole
Dream Pad
Magic Piano
Solo Sax
Choir
12-String
Kalimba
A.Bass
Strings
SynMallet
Drums #2
Lore
Harpsichord
DoubleReed
Bottles
Koto Trem
Bell Ring
SynthBass 1
Timp&Bells
Solo Synth
Pop
Magician
Piano 8'
Overture
Angels
Sitar 1
Tubular
Slap Bass
Pipe Organ
Wire
Drum #3
Bambu Trem
E.Piano 4
TubaFlugel
Voice Wave
Guitar 2
Metal Hit
SynthBass2
StringRise
Pan Wave
Hammer
Cloud Nine
Clav
Tenor Sax
Voices
Rock Guitar
WindBells
SynthBass3
Organ 1
Block
FingerSnap
MagicOrgan
E.Piano 2
Brass 2
FV Wave
PickGuitar
Digi-Bells
AnalogBass
Ping Wave
Vibe Hit
Pluck
Good & Bad
Digital 2
Mute Trp.
Stratos
Sitar 2
Flexatone
Digital 4
Soft Horns
HellsBells
Drop
Zephyr
E.Piano 3
SynthBrass
Digital 5
E.Guitar 1
Rhythm
Mono Synth
Hold.....
Wait.....
Surprise!!
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
