patc
Korg M3R
M3R
Krypton
Grand Piano
String Pad
Synth Stab
Spirits
Guitar
Vivaldi
Jazz Hits
Mondo Drum
Aurora
Touch Roads
Growl Sax
Violins
Lazer Sweep
Pan Pipes
Fretless
Voice Choir
Bass & Vibes
East of Java
Nocturnal
Perc. Organ
Valves
Finale
Synth*Res
Air Guitar
Phased Clav
Stereo Reed
PowerSplit
Kit1+MIDI
CloudBells
Tyne Piano
1NoteBrass
String Pizz
MeetMrBass
MetalVoice
Atmosphere
Sonata
Bass&E.P.
Kit2+MIDI
Solar Rings
Fosterism
Air Horns
Concerto
Haunted
Atlantix
Slap Clav
Brass Orch
Clar&Flute
Kit3+MIDI
InnerSpace
Pipe Organ
Harmonic 5
Quartet
Synced
Glass Voice
Rock Mutes
Ensemble
SpicySplit
AirMarimba
Jhada
Tyne Voices
Sax Section
Classical
Ready2Rock
Sparkles
Cloud City
Woodwinds
ReggaeMahn
Drum Pad
South Pole
Real Roads
Super Brass
Piano&Strin
DATAHeaven
BellVoices
Raga
Passages
Alpine
Jovo Drums
ZoneSwitch
Rock Organ
Brass 1&2
Bell Pad
Jungle City
Monsoon
Nasty Clav
Reed 5th
Orga&Syn
WoodenBell
Reflection
Wirly Trem
Horns&Reed
Orchestra
HyperSynth
Breathy
Bombay
Symphony
JamminDude
Africana
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
