patc
E-mu Proteus/2
Prot2
Solo Cello
Solo Viola
Solo Violin
Quartet
Solo Chamber
Arco Basses
Arco Celli
Arco Violas
Arco Violins
Marcato 1
Marcato 2
Legato Str
Concerto
Pizz Basses
Pizz Celli
Pizz Violas
Pizz Violins
Pizzicato 1
Pizzicato 2
Trem Strings
Tremulus
Strgs/Flutes
Resting Pad
Divertimento
Flute
Piccolo
Oboe
English Horn
Clarinet
BassClarinet
Bassoon
Contrbassoon
ChamberWinds
SectionWinds
Epilogue
Wind Stack
French Horn1
French Horn2
SectionHorns
Trumpet 1
Trumpet 2
TwoTrumpets
Harmon Mute
Trombone 1
Trombone 2
Tuba
Back Brass
Bright Brass
ChamberBrass
BrassStrings
Timpani
Gong/Cymbal
Bass/Snare+
Temple Block
Xylophone
Glocknspiel
Celesta
TubularBells
Percussion 1
Percussion 2
Harp
Harpstrings
Harpsikord
Notre Dame
Winter Signs
Deep Pad
Portamento
BellEnsemble
Cyberspace
PizzMoogBass
Marimbala
Grim Reaper
Tinker Bell
Carousel
Exotic Harp
Darn Saucers
Bronze Pad
Vibraphone
Astral Flute
Kool Bass
Sombre Winds
Space Cowboy
The Machine
Early Perc
Gently Now *
Piccolodeeyo
Infinite One
ShimmerWays*
Turbo Bass
Requiem
Wrong Room
Analog Pad
Chapel Organ
Electrovocal
Fat Boy Tuba
SawBass/Lead
Vienna Dream
Vertigo Pad
Tarkus Twin
RoomOfStrngs
Magic Bells
Reginatron
Sub It!
Psychlotron
CloudChamber
Sepulcher
Lurch Pluck
Pizz/Piccolo
Vampirical
String Thing
Galapagos
Square One**
SquareLink**
<*>
Sardonicus
Master Tron
Lo Wind Inst
Sympathetic
Wind Chimes
Boat Haus
Glitter God
Story Bass
Nice Night
ProphetLead**
ProphetLink**
Whistl'n Joe
Link2Shimmer*
Ascending
