patc
E-mu Proteus/1
Prot1
Stereo Piano
Hall Strings
InChoirIrie
BigCityBrass
Stereo Sax
Acoustic Gtr
Modern Gtr
Thunder Bass
MiniMoogBass
B3 Mod->Lesl
Phantazia
ZoundTrax
Vibe n Me
Tiki Threat
Rock Drums 1
Metal Vapor
Heaven
Verb Flute
El. Piano
Fr. Horn Sect
Velcty Falls
Stereo Mutes
StoneBs&Hrns
Slap/PopBass
Rap Bass
Special FX 1
Harmonic Syn
Beyond FM
Kyoto Forest
Balinesia
Latin Drums
Wind Chimes
Harpsikord
String Orch.
Human Voices
Baritone Sax
Solo Trumpet
12 String *
Modern Harp
Str.Bs/Piano
Mythical Pad
PianoBell
Noh Way!
Empyrean
Glocken
Wide Marimba
Latin Perc.
Space Bk.Gtr
Grand Piano
FlangeString
White Veil
Dark World
Miles Solos
SoloTrombone
Xprsiv El.Gtr
SpaceBassPad
Dune
RB's Wine
Octave Choir
Gitano
ThaiBathHse.
Medicine Drum
Radical Drum
Mltphn Arp 9
FMStylePiano
Isham Strings
We Ate Flangers
Space Clavier
Hard Trmp Am
Ball Game
Clean Strat
NozeBass/Pad
Wide Neck
Space Horn
Blue Ice
EmberedTines
Odd Vibes
Bright Steel
Native Power *
Insects
VibrantPiano
Emperor
NoiseFree LA
Orch. Brass
Lo Oct Bones
Synthibell
SpaceSteel
Jet **
Jet  **
SquarishLead
Synth String
Space Trmpt
Metal Throat
Light Mallet
Congablock
Hold&Sample
Piano Drama
Punctuate
Lunar Window
Reedy Keys
String Swell
Jingle Pad
Solo Lead
Buzzy Frets
Bass & Synth *
Gillectro
Pop Pad
BanJovi
Malletumba
SlipperyBass
Hall2Strgs**
Hall2Link**
WinstonGrand
STRings
Sharp Edge
Uboe
Vibes/Choir *
Solo Synth 3
Rock Gitaro
Animal 1 **
Animal **
Bed Tine
Mr Minister
Bone Face
Tremelo Vibe
Dulcimer
Block Head
Barber Pole
