patc
Ensoniq SD-1
SD-1
Dynamic Grn
Rude Guitar
I am alive
Stacked
Warm Bows
Elements
Alls fair 2
Soft words
Nu Winds
Lazer brass
Rack Bass
Jam-map-E
Digi moods
Arctic elate
Apollo
Tine Grnd
Inspired
Musak box
Orchestra
Red sky
Hard attack
Percuss me
Nice stack
Radium
Grease plus
Crystally
Vx organ
Dance gtr
Burn bass
Drum-map-E
Flugl + tenor
Vibrophone
Trombone
Chix grand
Accoustibass
Prs brushes
Grind organ
Jump
Multi organ
Guitar pads
Elec fret
Cmpresd kit
Accordion
Whistler
Wuz piano
Banjo
Pedal steel
Mandolin
Fanfare
Tubular bel
Churchtime
Mexi trump
Latino perc
Florida key
Tympani
Marimba
Kalimba
Steel drum
Glocknspiel
Widepunch
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
