patc
Ensoniq SQ-2
SQ2
Grand Act
Mystic
Dirt Guitar
Bassoon
Today's Organ
Reckoning
No Frets
L.A. Brass
Bishop
Analog Power
Piano & Strings
Neptune
Clarinet
French Horn
Strings & Brass
Space Percussion
Jazz Izz
String Section
Twelve Strings
New Horizon
Encore
Tinsel Town
Dyno Keys
Binary Keys
Clav
Harpsichord
Jazz Keys
Heavenly
Out Vox
Astro Vox
Pipe Organ
Organ 1
Organ 2
Organ 3
Organ 4
Steel String
Pedal Steel
Record Guitar
Slam Guitar
Chuk Guitar
Super Pad
Fascination
Outer Limits
Pulse Wave
Path Finder 
Burnin' Sax
Trumpet
Bari & Brass
Eternity
Forest Flute
Cresendo Strings
Bell & String
Velo Strings
Scoring Strings
Cello Like
Pizzicato
Top Synth
Perc Lead
Dyno Lead
Wailin'Synth
Rock Bass
Slam Bass
Rubber Bass
Burnin' Bass
Nineties Bass
Jazz Bass
Banjo
Minstrel
OrchestraHit
Wonder Years
Easter Island
Seduction
Blaster
Classic Bell
Metal Flute
New Bell
Mallets
Mod Percussion
Island Perc
Big Ol' Rock Kit
Top Forty Kit
R & B Kit 1
R & B Kit 2
Fusion Kit
Ballad Kit
Ol' Faithful Kit
Latin Kit
Beefy Kit
All Purpose Kit
Percussion 1
Percussion 2
Hybrid Kit
Synth Kit 1
Synth Kit 2
Hip Hop Kit
Out Kit
Eastern Perc
African Perc
Wind Chimes
Baby Grand
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
