patc
Korg T1/2/3
T1/2/3
Aeroglide
Piano 16
Brass 1
Ooh/Aah
Guitar 1
Bottle Bell
Fretless
Symphonic
Pan Flute
M1 Drums
Pan Mallet
E.Piano
Trumpet
I saw wind
Van Guitar
Vibes
Pick Bass
Sawstrings
Flute
Soft Pole
Night Dad
Organ 2
Solo Sax
Choir
12-Strings
Kalimba
A. Bass
Strings
Syn Mallet
Velo+Gate2
Lore
Harpsichord
DoubleReed
Kot Trem
Bell Ring
Synthbass 1
Super Pizz
Mono Synth
Pan drops
Dreampad 2
Piano 8'
Fanfare
Angles
Sitar 1
Tubular
uper Slap
Pipeorgan
48
Pitch Kit
Bambu Trem
E.Piano 4
TUBAFLUGEL
VOICE WAVE
GUITAR 2
SYNTHSWEEP
ROTO-BASS
ARCOSTRNG
SOFT-BELLS
THUNDER
CLOUD NINE
CLAV 1
TENOR SAX
VOICES
DISTGUITAR
WINDBELLS
PULL BASS
QUARTET
Block
Magic Voice
Magic Organ
Perc. Organ
Brass 2
M-Wavers
Digital 4
Digi Bells
SquareBass
Soundtrack
Busy Talk
Wild Pole
Echo Pad
Digital 12
Mute Trp.
Vox Voice
Sitar 2
Octapad
HammerBass
Soft Horns
Tri-Square
Rhythm
UpThe River
DWGS Clav
Synthbrass
Digital 5
E. Guitar 1
DWGS Bell
Slap Bass
Magic Ring
Tri-Synth
Whistler
One World
PCM Piano
Alto Sax
Spectrum 2
E.Bass
Marimba
Res-Synth1
Stringorch
Wavesweep1
T1 Drums
Steamsynth
Soft E.P.
Trombone
Wavesweep2
Banjo
Gamelan
Pick-Piano
Harp
Wavesweep3
Timpani
Pasqualina
Pad Piano
Harmonica
Vocoder
PICK Bass
Pot Covers
Da Voice
q
Bellsynth1
