patc
Yamaha VL1-m
VL1-m
Moby
Tenor Sax
Shakuhachi
FingerBass
Trumpet
Ossyncro
Tull Flute
Bagpipes
GuitarHero
Mizu Horne
Viol Inn
Endophone
JetLipBow
BowBamBoo
Bassoon
Digeritek
Backwards
Alto Sax
Pan Pipes
MelodyBass
Horn
50/50
C Flute
HurdyGurdy
JazzGuitar
Harmophone
Fiddler
Floboe
Yhokihi
BlueBottle
Clarinet
Jurassic
Gonzilla
Soprano 1
MouthKeys
Thump Bass
Cornet
Igneous
Alto Flute
Khaen
Cruncher
Marsaloboe
Eleanor
RichReed
Breath Bow
SquealerAT
Oboe
Maysbe?
BlownDrone
Loose Bari
Toots
Fretless
Tuba
Arpoon
Piccolo
Thai Reed
Flange
NuSoprPipe
Contraire
ClariLip
Conchise
Pastorale
Barker
FrenchBone
Dr.Bonky
Bell Miked
Blues Harp
Slap Bass
Muted Lips
Analunar
Andean
Sitar
Rock Pigs
Synth Lite
St. Ripper
Scat Harp
L7 Pluck
Flak
3 AM Blow
Yamasteel
MoreGrunge
Soprano 2
Ocarina
Upright
Alto&Trump
OldMini
Fyfe
Squeezebox
Mr. Mogue
HyperClari
DoubleBow
RuffWreck
Clavisynth
Claricord
TrumpNSax
QuiScivit?
Lees
Breath Sax
Bowed Saw
Birdland 
Fanfare 
Chaisaw 
Recorder
Harmonium
WonderBass
NuDblReed
Viowind 
Harmoweird
Cyberpluck
NuAltoPipe
Gerhard
Mad Tube
AcoEkoSyn
LooseTenor
Kokyu
Tube Bass
TrumpCard
PipeBowBow
BaroquePad
Outback
FuzzyBass
Wheed
Monteverdi
Sax Git
Cyberlsen
Clar&Flute
Saxes
Isn't Wah
