patc
Korg X5
X5
PipeDreams
X Piano
BigStrings
Asian Jung
Rock On!!!
GlockBells
FatRezBass
BreathyVox
Xanalog
[KrazyKit]
Transforms
Killer B
Pop Brass
Harp Gliss
BriteSteel
PingMallet
Upright
Velo Flute
LA Synth
[Combo Kit]
Wave Sweep
FunkyRoads
AnaStrings
Euro Pipe
Stratified
Crystallce
Dance Bass
Ghost Vox
FatFilterz
[Down Low]
Sputnik
Super Perc
BrassSwell
Lore
Follow Me
Logs&Bells
90's Bass
FreshWaves
MIDI Grand
[Mr. Gong]
LandingPad
M1 Piano
DynoString
Tamboura
Chruncher
Star Fire
SynthBass3
Woodwinds
Reso Waves
[Manimals]
Vortex
ClickOrgan
StereoHorn
MalletLoop
Flamenco
MetalGhost
Velo Pick
ooooooooze
Dr. Tapp
[Loop SFX]
TimeClocks
Classic EP
Cello Ens.
Godfather
Funk Guitr
RealGamlon
ChromeBass
Real Shaku
Split Sync
[Nature]
Syn Tronic
Super BX-3
Trump Ens
Jaw Harp
Rock Chuga
ThelceMan
Velo Slap
Flutter
Swell Pad
[Natives!]
Quarks
Dyno Tines
VeloFlugel
Polka Box
FeedbackGt
Swiss Box
Big Mini
Arabesque
Syn Brass
[DrillMe!]
Universe X
Big Organ
Ethno Violin
Real Sitar
Greek Gtr.
Midi Bells
Stick Bass
SopranoVox
Solo Synth
[Jet Star]
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
