patc
XG SFX Voices
XGSFX
Cutting Nz
Cutting Nz2
-
Str Slap
-
-
-
-
-
-
-
-
-
-
-
-
Fl.KClik
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
Rain
Thunder
Wind
Stream
Bubble
Feed
-
-
-
-
-
-
-
-
-
-
Dog
Horse
Bird 2
-
-
-
Ghost
Maou
-
-
-
-
-
-
-
-
Telephone Dial
Door Squeak
Door Slam
Scratch
Scratch 2
Wind Chime
Telephone 2
-
-
-
-
-
-
-
-
-
Car Engine
Car Stop
Car Pass
Car Crash
Siren
Train
Jetplane
Starship
Burst
Coaster
Submarine
-
-
-
-
-
Laughing
Scream
Punch
Heart
Footstep
-
-
-
-
-
-
-
-
-
-
-
Machine Gun
Laser Gun
Explosion
Firework